// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      // case TargetPlatform.iOS:
      //   return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBI2cKGZ7dgeiNx6S5_UEb6h1LMVfXqmV8',
    appId: '1:448022630522:web:0fd163deefc05b66aeebc3',
    messagingSenderId: '448022630522',
    projectId: 'skl-notification',
    authDomain: 'skl-notification.firebaseapp.com',
    storageBucket: 'skl-notification.firebasestorage.app',
    measurementId: 'G-9F9NE0HF6M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLKzcepnO1rbBd9j-YMxMqCG8RUyo3QTw',
    appId: '1:448022630522:android:35881750aabeba92aeebc3',
    messagingSenderId: '448022630522',
    projectId: 'skl-notification',
    storageBucket: 'skl-notification.firebasestorage.app',
  );

  // static const FirebaseOptions ios = FirebaseOptions(
  //   apiKey: 'AIzaSyCetSuqB8SujRlCABj9vcF3NQjM_fPs8eI',
  //   appId: '1:448022630522:ios:3b30515cae354410aeebc3',
  //   messagingSenderId: '448022630522',
  //   projectId: 'skl-notification',
  //   storageBucket: 'skl-notification.firebasestorage.app',
  //   iosBundleId: 'com.leaveApp.SklHrApp.sklLeave',
  // );
}
