// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4Y-EcOiBUehW3KxpBhXpG7IUJkPuJ7mY',
    appId: '1:741311595283:web:3b3c14ce9a5eed8e4ed0e6',
    messagingSenderId: '741311595283',
    projectId: 'leave-app-7db96',
    authDomain: 'leave-app-7db96.firebaseapp.com',
    storageBucket: 'leave-app-7db96.firebasestorage.app',
    measurementId: 'G-0MNM6LCKY0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABVfUDKnuT27l88Nhc9qwxzNqRzb4lvRM',
    appId: '1:741311595283:android:b347db4d74b887624ed0e6',
    messagingSenderId: '741311595283',
    projectId: 'leave-app-7db96',
    storageBucket: 'leave-app-7db96.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQlh3EaJj_Cy0jvzg6fm2kl11JDKE5258',
    appId: '1:741311595283:ios:505d915fe06587144ed0e6',
    messagingSenderId: '741311595283',
    projectId: 'leave-app-7db96',
    storageBucket: 'leave-app-7db96.firebasestorage.app',
    iosBundleId: 'com.leaveApp.SklHrApp.sklLeave',
  );

}